os: linux
dist: bionic
language: c
services: docker

jdk: openjdk11
addons:
  hosts:
    - mariadb.example.com


cache:
  apt: true
  ccache: true
  directories:
    - $HOME/docker

before_install:
  - git clone https://github.com/mariadb-corporation/connector-test-machine.git
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - |-
    if [ -z "$SERVER_BRANCH" ] ; then
      case $TRAVIS_OS_NAME in
        windows)
          choco install openjdk11 maven
          export PATH=$(cmd.exe //c "refreshenv > nul & C:\Progra~1\Git\bin\bash -c 'echo \$PATH' ")
          connector-test-machine/launch.bat -t "$srv" -v "$v" -d testc
          ;;
        linux)
          source connector-test-machine/launch.sh -t "$srv" -v "$v" -d testc -n 0 -l "$local" -p "$packet"  -n "$native"
          ;;
      esac
    fi


env: LOCAL=0


jobs:
  allow_failures:
    - env: srv=build v=10.6
  include:
    - env: srv=mariadb v=10.5
      os: windows
      language: shell
    - env: srv=mariadb v=10.2 local=1
    - env: srv=mariadb v=10.3 local=1
    - env: srv=mariadb v=10.4 local=1
    - env: srv=mariadb v=10.6 local=1
    - env: srv=mariadb v=10.5
    - env: srv=maxscale
    - env: srv=build v=10.6
    - env: srv=mysql v=5.7 native=1
    - env: srv=mysql v=8.0 native=1
    - env: srv=skysql
    - env: srv=skysql-ha
    - env: SERVER_BRANCH=10.6
    - env: SERVER_BRANCH=10.6 TEST_OPTION=--ps-protocol

script: ./travis.sh

